import type { InsertRosterPlayer } from "@shared/schema";

export const nflRosters2026: InsertRosterPlayer[] = [
  // ========== ARI - Arizona Cardinals ==========
  { teamCode: "ARI", name: "Kyler Murray", position: "QB", depthOrder: 1, age: 28, capHit: 46.1, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Clayton Tune", position: "QB", depthOrder: 2, age: 26, capHit: 1.2, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "James Conner", position: "RB", depthOrder: 1, age: 31, capHit: 9.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Marvin Harrison Jr", position: "WR", depthOrder: 1, age: 23, capHit: 7.8, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Michael Wilson", position: "WR", depthOrder: 2, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Zay Jones", position: "WR", depthOrder: 3, age: 29, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Trey McBride", position: "TE", depthOrder: 1, age: 25, capHit: 1.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Paris Johnson Jr", position: "OT", depthOrder: 1, age: 23, capHit: 5.8, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Kelvin Beachum", position: "OT", depthOrder: 2, age: 36, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Evan Brown", position: "OL", depthOrder: 1, age: 29, capHit: 5.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Will Hernandez", position: "OL", depthOrder: 2, age: 29, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "BJ Ojulari", position: "EDGE", depthOrder: 1, age: 24, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Bilal Nichols", position: "DT", depthOrder: 1, age: 28, capHit: 9.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Kyzir White", position: "LB", depthOrder: 1, age: 29, capHit: 6.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Budda Baker", position: "S", depthOrder: 1, age: 30, capHit: 14.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Sean Murphy-Bunting", position: "CB", depthOrder: 1, age: 28, capHit: 5.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ARI", name: "Jalen Thompson", position: "S", depthOrder: 2, age: 27, capHit: 7.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== ATL - Atlanta Falcons ==========
  { teamCode: "ATL", name: "Michael Penix Jr", position: "QB", depthOrder: 1, age: 24, capHit: 5.6, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Bijan Robinson", position: "RB", depthOrder: 1, age: 23, capHit: 3.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Drake London", position: "WR", depthOrder: 1, age: 24, capHit: 5.2, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Darnell Mooney", position: "WR", depthOrder: 2, age: 27, capHit: 8.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Ray-Ray McCloud", position: "WR", depthOrder: 3, age: 28, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Kyle Pitts", position: "TE", depthOrder: 1, age: 26, capHit: 10.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Jake Matthews", position: "OT", depthOrder: 1, age: 33, capHit: 18.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Kaleb McGary", position: "OT", depthOrder: 2, age: 30, capHit: 16.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Chris Lindstrom", position: "OL", depthOrder: 1, age: 28, capHit: 17.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Drew Dalman", position: "OL", depthOrder: 2, age: 27, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Grady Jarrett", position: "DT", depthOrder: 1, age: 31, capHit: 16.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Arnold Ebiketie", position: "EDGE", depthOrder: 1, age: 26, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Jessie Bates III", position: "S", depthOrder: 1, age: 28, capHit: 16.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "AJ Terrell", position: "CB", depthOrder: 1, age: 26, capHit: 17.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Troy Andersen", position: "LB", depthOrder: 1, age: 26, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "ATL", name: "Kaden Elliss", position: "LB", depthOrder: 2, age: 28, capHit: 5.5, contractYears: 2, status: "active", sport: "NFL" },

  // ========== BAL - Baltimore Ravens ==========
  { teamCode: "BAL", name: "Lamar Jackson", position: "QB", depthOrder: 1, age: 29, capHit: 52.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Josh Johnson", position: "QB", depthOrder: 2, age: 38, capHit: 1.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Derrick Henry", position: "RB", depthOrder: 1, age: 32, capHit: 16.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Zay Flowers", position: "WR", depthOrder: 1, age: 24, capHit: 3.2, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Rashod Bateman", position: "WR", depthOrder: 2, age: 26, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Nelson Agholor", position: "WR", depthOrder: 3, age: 33, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Mark Andrews", position: "TE", depthOrder: 1, age: 31, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Ronnie Stanley", position: "OT", depthOrder: 1, age: 30, capHit: 18.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Roger Rosengarten", position: "OT", depthOrder: 2, age: 24, capHit: 2.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Tyler Linderbaum", position: "OL", depthOrder: 1, age: 26, capHit: 4.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Andrew Vorhees", position: "OL", depthOrder: 2, age: 27, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Roquan Smith", position: "LB", depthOrder: 1, age: 28, capHit: 20.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Kyle Hamilton", position: "S", depthOrder: 1, age: 24, capHit: 5.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Marlon Humphrey", position: "CB", depthOrder: 1, age: 29, capHit: 19.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Brandon Stephens", position: "CB", depthOrder: 2, age: 28, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Justin Madubuike", position: "DT", depthOrder: 1, age: 28, capHit: 18.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "BAL", name: "Marcus Williams", position: "S", depthOrder: 2, age: 28, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== BUF - Buffalo Bills ==========
  { teamCode: "BUF", name: "Josh Allen", position: "QB", depthOrder: 1, age: 30, capHit: 43.5, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Mitchell Trubisky", position: "QB", depthOrder: 2, age: 32, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "James Cook", position: "RB", depthOrder: 1, age: 25, capHit: 2.2, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Khalil Shakir", position: "WR", depthOrder: 1, age: 25, capHit: 1.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Curtis Samuel", position: "WR", depthOrder: 2, age: 29, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Keon Coleman", position: "WR", depthOrder: 3, age: 23, capHit: 1.8, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Dalton Kincaid", position: "TE", depthOrder: 1, age: 25, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Dion Dawkins", position: "OT", depthOrder: 1, age: 31, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Spencer Brown", position: "OT", depthOrder: 2, age: 27, capHit: 6.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Connor McGovern", position: "OL", depthOrder: 1, age: 28, capHit: 4.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Von Miller", position: "EDGE", depthOrder: 1, age: 37, capHit: 17.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Greg Rousseau", position: "EDGE", depthOrder: 2, age: 25, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Ed Oliver", position: "DT", depthOrder: 1, age: 27, capHit: 18.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Rasul Douglas", position: "CB", depthOrder: 1, age: 30, capHit: 9.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Taron Johnson", position: "CB", depthOrder: 2, age: 28, capHit: 6.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Taylor Rapp", position: "S", depthOrder: 1, age: 28, capHit: 5.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "BUF", name: "Terrel Bernard", position: "LB", depthOrder: 1, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== CAR - Carolina Panthers ==========
  { teamCode: "CAR", name: "Bryce Young", position: "QB", depthOrder: 1, age: 24, capHit: 8.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Andy Dalton", position: "QB", depthOrder: 2, age: 39, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Chuba Hubbard", position: "RB", depthOrder: 1, age: 26, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Diontae Johnson", position: "WR", depthOrder: 1, age: 29, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Adam Thielen", position: "WR", depthOrder: 2, age: 36, capHit: 7.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Xavier Legette", position: "WR", depthOrder: 3, age: 24, capHit: 2.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Tommy Tremble", position: "TE", depthOrder: 1, age: 25, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Ikem Ekwonu", position: "OT", depthOrder: 1, age: 24, capHit: 6.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Taylor Moton", position: "OT", depthOrder: 2, age: 30, capHit: 16.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Austin Corbett", position: "OL", depthOrder: 1, age: 29, capHit: 7.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Jaycee Horn", position: "CB", depthOrder: 1, age: 26, capHit: 7.2, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Derrick Brown", position: "DT", depthOrder: 1, age: 27, capHit: 6.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Shaq Thompson", position: "LB", depthOrder: 1, age: 31, capHit: 11.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Xavier Woods", position: "S", depthOrder: 1, age: 29, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CAR", name: "Josey Jewell", position: "LB", depthOrder: 2, age: 30, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },

  // ========== CHI - Chicago Bears ==========
  { teamCode: "CHI", name: "Caleb Williams", position: "QB", depthOrder: 1, age: 24, capHit: 8.6, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Tyson Bagent", position: "QB", depthOrder: 2, age: 26, capHit: 1.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "D'Andre Swift", position: "RB", depthOrder: 1, age: 27, capHit: 8.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "DJ Moore", position: "WR", depthOrder: 1, age: 29, capHit: 22.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Rome Odunze", position: "WR", depthOrder: 2, age: 23, capHit: 5.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Keenan Allen", position: "WR", depthOrder: 3, age: 34, capHit: 12.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Cole Kmet", position: "TE", depthOrder: 1, age: 26, capHit: 10.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Braxton Jones", position: "OT", depthOrder: 1, age: 26, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Darnell Wright", position: "OT", depthOrder: 2, age: 24, capHit: 4.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Nate Davis", position: "OL", depthOrder: 1, age: 28, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Montez Sweat", position: "EDGE", depthOrder: 1, age: 29, capHit: 23.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "DeMarcus Walker", position: "EDGE", depthOrder: 2, age: 30, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Andrew Billings", position: "DT", depthOrder: 1, age: 30, capHit: 5.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Tremaine Edmunds", position: "LB", depthOrder: 1, age: 27, capHit: 18.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "TJ Edwards", position: "LB", depthOrder: 2, age: 28, capHit: 9.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Jaylon Johnson", position: "CB", depthOrder: 1, age: 26, capHit: 17.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CHI", name: "Kevin Byard", position: "S", depthOrder: 1, age: 31, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },

  // ========== CIN - Cincinnati Bengals ==========
  { teamCode: "CIN", name: "Joe Burrow", position: "QB", depthOrder: 1, age: 29, capHit: 55.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Jake Browning", position: "QB", depthOrder: 2, age: 28, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Zack Moss", position: "RB", depthOrder: 1, age: 27, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Ja'Marr Chase", position: "WR", depthOrder: 1, age: 26, capHit: 30.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Tee Higgins", position: "WR", depthOrder: 2, age: 27, capHit: 21.8, contractYears: 1, status: "franchise_tag", sport: "NFL" },
  { teamCode: "CIN", name: "Andrei Iosivas", position: "WR", depthOrder: 3, age: 25, capHit: 1.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Mike Gesicki", position: "TE", depthOrder: 1, age: 29, capHit: 7.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Orlando Brown Jr", position: "OT", depthOrder: 1, age: 29, capHit: 16.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Amarius Mims", position: "OT", depthOrder: 2, age: 23, capHit: 3.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Alex Cappa", position: "OL", depthOrder: 1, age: 30, capHit: 11.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Ted Karras", position: "OL", depthOrder: 2, age: 31, capHit: 6.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Trey Hendrickson", position: "EDGE", depthOrder: 1, age: 30, capHit: 21.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Sam Hubbard", position: "EDGE", depthOrder: 2, age: 29, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "DJ Reader", position: "DT", depthOrder: 1, age: 30, capHit: 13.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Cam Taylor-Britt", position: "CB", depthOrder: 1, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CIN", name: "Dax Hill", position: "S", depthOrder: 1, age: 25, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },

  // ========== CLE - Cleveland Browns ==========
  { teamCode: "CLE", name: "Deshaun Watson", position: "QB", depthOrder: 1, age: 31, capHit: 54.9, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Jameis Winston", position: "QB", depthOrder: 2, age: 32, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Nick Chubb", position: "RB", depthOrder: 1, age: 30, capHit: 12.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Jerry Jeudy", position: "WR", depthOrder: 1, age: 27, capHit: 11.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Amari Cooper", position: "WR", depthOrder: 2, age: 32, capHit: 20.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Elijah Moore", position: "WR", depthOrder: 3, age: 25, capHit: 4.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "David Njoku", position: "TE", depthOrder: 1, age: 28, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Jedrick Wills Jr", position: "OT", depthOrder: 1, age: 26, capHit: 13.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Jack Conklin", position: "OT", depthOrder: 2, age: 30, capHit: 14.0, contractYears: 1, status: "injured", sport: "NFL" },
  { teamCode: "CLE", name: "Joel Bitonio", position: "OL", depthOrder: 1, age: 35, capHit: 13.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Ethan Pocic", position: "OL", depthOrder: 2, age: 30, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Myles Garrett", position: "EDGE", depthOrder: 1, age: 30, capHit: 31.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Za'Darius Smith", position: "EDGE", depthOrder: 2, age: 33, capHit: 10.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Dalvin Tomlinson", position: "DT", depthOrder: 1, age: 30, capHit: 12.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Denzel Ward", position: "CB", depthOrder: 1, age: 28, capHit: 21.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Martin Emerson Jr", position: "CB", depthOrder: 2, age: 25, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Grant Delpit", position: "S", depthOrder: 1, age: 26, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "CLE", name: "Jeremiah Owusu-Koramoah", position: "LB", depthOrder: 1, age: 26, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },

  // ========== DAL - Dallas Cowboys ==========
  { teamCode: "DAL", name: "Dak Prescott", position: "QB", depthOrder: 1, age: 33, capHit: 55.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Cooper Rush", position: "QB", depthOrder: 2, age: 31, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Ezekiel Elliott", position: "RB", depthOrder: 1, age: 31, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "CeeDee Lamb", position: "WR", depthOrder: 1, age: 27, capHit: 34.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Brandin Cooks", position: "WR", depthOrder: 2, age: 33, capHit: 8.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Jalen Tolbert", position: "WR", depthOrder: 3, age: 26, capHit: 1.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Jake Ferguson", position: "TE", depthOrder: 1, age: 26, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Tyler Smith", position: "OT", depthOrder: 1, age: 24, capHit: 4.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Terence Steele", position: "OT", depthOrder: 2, age: 28, capHit: 6.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Zack Martin", position: "OL", depthOrder: 1, age: 36, capHit: 16.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Tyler Biadasz", position: "OL", depthOrder: 2, age: 28, capHit: 8.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Micah Parsons", position: "EDGE", depthOrder: 1, age: 27, capHit: 11.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "DeMarcus Lawrence", position: "EDGE", depthOrder: 2, age: 34, capHit: 17.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Quinnen Williams", position: "DT", depthOrder: 1, age: 28, capHit: 25.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Osa Odighizuwa", position: "DT", depthOrder: 2, age: 27, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Trevon Diggs", position: "CB", depthOrder: 1, age: 28, capHit: 17.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "DaRon Bland", position: "CB", depthOrder: 2, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Malik Hooker", position: "S", depthOrder: 1, age: 29, capHit: 8.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DAL", name: "Logan Wilson", position: "LB", depthOrder: 1, age: 28, capHit: 11.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== DEN - Denver Broncos ==========
  { teamCode: "DEN", name: "Bo Nix", position: "QB", depthOrder: 1, age: 25, capHit: 5.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Jarrett Stidham", position: "QB", depthOrder: 2, age: 29, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Javonte Williams", position: "RB", depthOrder: 1, age: 25, capHit: 4.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Courtland Sutton", position: "WR", depthOrder: 1, age: 30, capHit: 15.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Marvin Mims Jr", position: "WR", depthOrder: 2, age: 23, capHit: 1.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Troy Franklin", position: "WR", depthOrder: 3, age: 23, capHit: 1.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Adam Trautman", position: "TE", depthOrder: 1, age: 28, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Garett Bolles", position: "OT", depthOrder: 1, age: 33, capHit: 17.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Mike McGlinchey", position: "OT", depthOrder: 2, age: 30, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Lloyd Cushenberry III", position: "OL", depthOrder: 1, age: 27, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Quinn Meinerz", position: "OL", depthOrder: 2, age: 27, capHit: 5.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Pat Surtain II", position: "CB", depthOrder: 1, age: 25, capHit: 8.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Zach Allen", position: "DT", depthOrder: 1, age: 28, capHit: 15.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Jonathon Cooper", position: "EDGE", depthOrder: 1, age: 28, capHit: 5.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Nik Bonitto", position: "EDGE", depthOrder: 2, age: 25, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Alex Singleton", position: "LB", depthOrder: 1, age: 31, capHit: 4.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DEN", name: "Justin Simmons", position: "S", depthOrder: 1, age: 31, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },

  // ========== DET - Detroit Lions ==========
  { teamCode: "DET", name: "Jared Goff", position: "QB", depthOrder: 1, age: 31, capHit: 42.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Hendon Hooker", position: "QB", depthOrder: 2, age: 27, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Jahmyr Gibbs", position: "RB", depthOrder: 1, age: 23, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "David Montgomery", position: "RB", depthOrder: 2, age: 28, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Amon-Ra St. Brown", position: "WR", depthOrder: 1, age: 26, capHit: 28.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Jameson Williams", position: "WR", depthOrder: 2, age: 24, capHit: 4.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Kalif Raymond", position: "WR", depthOrder: 3, age: 30, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Sam LaPorta", position: "TE", depthOrder: 1, age: 24, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Penei Sewell", position: "OT", depthOrder: 1, age: 25, capHit: 10.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Dan Skipper", position: "OT", depthOrder: 2, age: 31, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Frank Ragnow", position: "OL", depthOrder: 1, age: 29, capHit: 16.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Graham Glasgow", position: "OL", depthOrder: 2, age: 32, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Aidan Hutchinson", position: "EDGE", depthOrder: 1, age: 25, capHit: 7.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "James Houston", position: "EDGE", depthOrder: 2, age: 26, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Alim McNeill", position: "DT", depthOrder: 1, age: 26, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Alex Anzalone", position: "LB", depthOrder: 1, age: 30, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Terrion Arnold", position: "CB", depthOrder: 1, age: 22, capHit: 4.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Brian Branch", position: "S", depthOrder: 1, age: 24, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "Kerby Joseph", position: "S", depthOrder: 2, age: 25, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "DET", name: "DJ Reed", position: "CB", depthOrder: 2, age: 28, capHit: 16.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== GB - Green Bay Packers ==========
  { teamCode: "GB", name: "Jordan Love", position: "QB", depthOrder: 1, age: 27, capHit: 45.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Sean Clifford", position: "QB", depthOrder: 2, age: 27, capHit: 1.2, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Josh Jacobs", position: "RB", depthOrder: 1, age: 28, capHit: 12.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Jayden Reed", position: "WR", depthOrder: 1, age: 25, capHit: 1.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Christian Watson", position: "WR", depthOrder: 2, age: 26, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Romeo Doubs", position: "WR", depthOrder: 3, age: 25, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Luke Musgrave", position: "TE", depthOrder: 1, age: 25, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Rasheed Walker", position: "OT", depthOrder: 1, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Zach Tom", position: "OT", depthOrder: 2, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Josh Myers", position: "OL", depthOrder: 1, age: 27, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Elgton Jenkins", position: "OL", depthOrder: 2, age: 29, capHit: 12.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Rashan Gary", position: "EDGE", depthOrder: 1, age: 27, capHit: 12.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Preston Smith", position: "EDGE", depthOrder: 2, age: 32, capHit: 8.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Kenny Clark", position: "DT", depthOrder: 1, age: 29, capHit: 15.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Quay Walker", position: "LB", depthOrder: 1, age: 25, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "GB", name: "Xavier McKinney", position: "S", depthOrder: 1, age: 26, capHit: 13.0, contractYears: 3, status: "active", sport: "NFL" },

  // ========== HOU - Houston Texans ==========
  { teamCode: "HOU", name: "CJ Stroud", position: "QB", depthOrder: 1, age: 24, capHit: 6.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Davis Mills", position: "QB", depthOrder: 2, age: 27, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Joe Mixon", position: "RB", depthOrder: 1, age: 30, capHit: 9.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Nico Collins", position: "WR", depthOrder: 1, age: 26, capHit: 24.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Tank Dell", position: "WR", depthOrder: 2, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Dalton Schultz", position: "TE", depthOrder: 1, age: 28, capHit: 9.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Laremy Tunsil", position: "OT", depthOrder: 1, age: 31, capHit: 24.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Tytus Howard", position: "OT", depthOrder: 2, age: 28, capHit: 16.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Juice Scruggs", position: "OL", depthOrder: 1, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Kenyon Green", position: "OL", depthOrder: 2, age: 24, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Will Anderson Jr", position: "EDGE", depthOrder: 1, age: 24, capHit: 8.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Danielle Hunter", position: "EDGE", depthOrder: 2, age: 31, capHit: 18.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Foley Fatukasi", position: "DT", depthOrder: 1, age: 30, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Derek Stingley Jr", position: "CB", depthOrder: 1, age: 24, capHit: 7.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Jimmie Ward", position: "S", depthOrder: 1, age: 33, capHit: 7.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "HOU", name: "Azeez Al-Shaair", position: "LB", depthOrder: 1, age: 28, capHit: 8.5, contractYears: 2, status: "active", sport: "NFL" },

  // ========== IND - Indianapolis Colts ==========
  { teamCode: "IND", name: "Anthony Richardson", position: "QB", depthOrder: 1, age: 23, capHit: 7.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Jonathan Taylor", position: "RB", depthOrder: 1, age: 27, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Michael Pittman Jr", position: "WR", depthOrder: 1, age: 28, capHit: 13.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Josh Downs", position: "WR", depthOrder: 2, age: 24, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Mo Alie-Cox", position: "TE", depthOrder: 1, age: 31, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Bernhard Raimann", position: "OT", depthOrder: 1, age: 27, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Braden Smith", position: "OT", depthOrder: 2, age: 29, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Ryan Kelly", position: "OL", depthOrder: 1, age: 31, capHit: 14.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Quenton Nelson", position: "OL", depthOrder: 2, age: 30, capHit: 20.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Kwity Paye", position: "EDGE", depthOrder: 1, age: 27, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "DeForest Buckner", position: "DT", depthOrder: 1, age: 32, capHit: 23.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Grover Stewart", position: "DT", depthOrder: 2, age: 30, capHit: 12.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Zaire Franklin", position: "LB", depthOrder: 1, age: 28, capHit: 8.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Sauce Gardner", position: "CB", depthOrder: 1, age: 25, capHit: 30.1, contractYears: 5, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Charvarius Ward", position: "CB", depthOrder: 2, age: 30, capHit: 20.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Julian Blackmon", position: "S", depthOrder: 1, age: 27, capHit: 6.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "IND", name: "Camryn Bynum", position: "S", depthOrder: 2, age: 27, capHit: 15.0, contractYears: 3, status: "active", sport: "NFL" },

  // ========== JAX - Jacksonville Jaguars ==========
  { teamCode: "JAX", name: "Trevor Lawrence", position: "QB", depthOrder: 1, age: 26, capHit: 45.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Mac Jones", position: "QB", depthOrder: 2, age: 27, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Travis Etienne", position: "RB", depthOrder: 1, age: 27, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Brian Thomas Jr", position: "WR", depthOrder: 1, age: 23, capHit: 4.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Christian Kirk", position: "WR", depthOrder: 2, age: 28, capHit: 18.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Jakobi Meyers", position: "WR", depthOrder: 3, age: 28, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Evan Engram", position: "TE", depthOrder: 1, age: 31, capHit: 12.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Cam Robinson", position: "OT", depthOrder: 1, age: 29, capHit: 18.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Anton Harrison", position: "OT", depthOrder: 2, age: 23, capHit: 5.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Brandon Scherff", position: "OL", depthOrder: 1, age: 34, capHit: 12.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Luke Fortner", position: "OL", depthOrder: 2, age: 27, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Josh Hines-Allen", position: "EDGE", depthOrder: 1, age: 28, capHit: 17.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Travon Walker", position: "EDGE", depthOrder: 2, age: 25, capHit: 8.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "DaVon Hamilton", position: "DT", depthOrder: 1, age: 28, capHit: 4.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Foye Oluokun", position: "LB", depthOrder: 1, age: 30, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "JAX", name: "Andre Cisco", position: "S", depthOrder: 1, age: 26, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },

  // ========== KC - Kansas City Chiefs ==========
  { teamCode: "KC", name: "Patrick Mahomes", position: "QB", depthOrder: 1, age: 30, capHit: 46.8, contractYears: 7, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Carson Wentz", position: "QB", depthOrder: 2, age: 33, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Isiah Pacheco", position: "RB", depthOrder: 1, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Xavier Worthy", position: "WR", depthOrder: 1, age: 22, capHit: 3.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Marquise Brown", position: "WR", depthOrder: 2, age: 28, capHit: 11.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "JuJu Smith-Schuster", position: "WR", depthOrder: 3, age: 30, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Travis Kelce", position: "TE", depthOrder: 1, age: 36, capHit: 17.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Jawaan Taylor", position: "OT", depthOrder: 1, age: 27, capHit: 16.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Wanya Morris", position: "OT", depthOrder: 2, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Creed Humphrey", position: "OL", depthOrder: 1, age: 26, capHit: 4.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Joe Thuney", position: "OL", depthOrder: 2, age: 32, capHit: 16.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Chris Jones", position: "DT", depthOrder: 1, age: 31, capHit: 31.7, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "George Karlaftis", position: "EDGE", depthOrder: 1, age: 25, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Felix Anudike-Uzomah", position: "EDGE", depthOrder: 2, age: 24, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Nick Bolton", position: "LB", depthOrder: 1, age: 26, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Trent McDuffie", position: "CB", depthOrder: 1, age: 25, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "KC", name: "Justin Reid", position: "S", depthOrder: 1, age: 28, capHit: 10.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== LAC - Los Angeles Chargers ==========
  { teamCode: "LAC", name: "Justin Herbert", position: "QB", depthOrder: 1, age: 28, capHit: 52.5, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Easton Stick", position: "QB", depthOrder: 2, age: 29, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "JK Dobbins", position: "RB", depthOrder: 1, age: 27, capHit: 5.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Ladd McConkey", position: "WR", depthOrder: 1, age: 24, capHit: 1.8, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Quentin Johnston", position: "WR", depthOrder: 2, age: 24, capHit: 4.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Joshua Palmer", position: "WR", depthOrder: 3, age: 26, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Will Dissly", position: "TE", depthOrder: 1, age: 29, capHit: 6.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Rashawn Slater", position: "OT", depthOrder: 1, age: 27, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Joe Alt", position: "OT", depthOrder: 2, age: 22, capHit: 6.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Zion Johnson", position: "OL", depthOrder: 1, age: 26, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Bradley Bozeman", position: "OL", depthOrder: 2, age: 30, capHit: 5.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Khalil Mack", position: "EDGE", depthOrder: 1, age: 35, capHit: 17.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Joey Bosa", position: "EDGE", depthOrder: 2, age: 31, capHit: 26.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Odafe Oweh", position: "EDGE", depthOrder: 3, age: 26, capHit: 15.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Poona Ford", position: "DT", depthOrder: 1, age: 30, capHit: 6.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Asante Samuel Jr", position: "CB", depthOrder: 1, age: 26, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Derwin James Jr", position: "S", depthOrder: 1, age: 29, capHit: 19.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAC", name: "Kenneth Murray Jr", position: "LB", depthOrder: 1, age: 27, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },

  // ========== LAR - Los Angeles Rams ==========
  { teamCode: "LAR", name: "Matthew Stafford", position: "QB", depthOrder: 1, age: 38, capHit: 32.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Jimmy Garoppolo", position: "QB", depthOrder: 2, age: 34, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Kyren Williams", position: "RB", depthOrder: 1, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Puka Nacua", position: "WR", depthOrder: 1, age: 24, capHit: 1.8, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Cooper Kupp", position: "WR", depthOrder: 2, age: 33, capHit: 22.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Demarcus Robinson", position: "WR", depthOrder: 3, age: 31, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Tyler Higbee", position: "TE", depthOrder: 1, age: 32, capHit: 7.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Alaric Jackson", position: "OT", depthOrder: 1, age: 28, capHit: 5.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Rob Havenstein", position: "OT", depthOrder: 2, age: 33, capHit: 11.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Steve Avila", position: "OL", depthOrder: 1, age: 25, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Jonah Jackson", position: "OL", depthOrder: 2, age: 29, capHit: 13.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Byron Young", position: "EDGE", depthOrder: 1, age: 25, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Kobie Turner", position: "DT", depthOrder: 1, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Jalen Ramsey", position: "CB", depthOrder: 1, age: 31, capHit: 22.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Tre'Davious White", position: "CB", depthOrder: 2, age: 31, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Quentin Lake", position: "S", depthOrder: 1, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LAR", name: "Ernest Jones IV", position: "LB", depthOrder: 1, age: 25, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },

  // ========== LV - Las Vegas Raiders ==========
  { teamCode: "LV", name: "Geno Smith", position: "QB", depthOrder: 1, age: 35, capHit: 25.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Aidan O'Connell", position: "QB", depthOrder: 2, age: 26, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Zamir White", position: "RB", depthOrder: 1, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Tre Tucker", position: "WR", depthOrder: 1, age: 24, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Michael Gallup", position: "WR", depthOrder: 2, age: 29, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Brock Bowers", position: "TE", depthOrder: 1, age: 23, capHit: 4.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Kolton Miller", position: "OT", depthOrder: 1, age: 29, capHit: 18.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Thayer Munford Jr", position: "OT", depthOrder: 2, age: 27, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Andre James", position: "OL", depthOrder: 1, age: 28, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Maxx Crosby", position: "EDGE", depthOrder: 1, age: 28, capHit: 28.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Malcolm Koonce", position: "EDGE", depthOrder: 2, age: 27, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Christian Wilkins", position: "DT", depthOrder: 1, age: 29, capHit: 22.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Robert Spillane", position: "LB", depthOrder: 1, age: 29, capHit: 6.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Nate Hobbs", position: "CB", depthOrder: 1, age: 26, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Marcus Epps", position: "S", depthOrder: 1, age: 29, capHit: 7.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "LV", name: "Jack Jones", position: "CB", depthOrder: 2, age: 27, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },

  // ========== MIA - Miami Dolphins ==========
  { teamCode: "MIA", name: "Tua Tagovailoa", position: "QB", depthOrder: 1, age: 28, capHit: 43.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Mike White", position: "QB", depthOrder: 2, age: 30, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "De'Von Achane", position: "RB", depthOrder: 1, age: 23, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Jaylen Waddle", position: "WR", depthOrder: 1, age: 26, capHit: 25.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Odell Beckham Jr", position: "WR", depthOrder: 2, age: 33, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Jonnu Smith", position: "TE", depthOrder: 1, age: 30, capHit: 6.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Terron Armstead", position: "OT", depthOrder: 1, age: 33, capHit: 18.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Austin Jackson", position: "OT", depthOrder: 2, age: 26, capHit: 8.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Connor Williams", position: "OL", depthOrder: 1, age: 28, capHit: 10.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Robert Hunt", position: "OL", depthOrder: 2, age: 27, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Bradley Chubb", position: "EDGE", depthOrder: 1, age: 30, capHit: 22.0, contractYears: 2, status: "injured", sport: "NFL" },
  { teamCode: "MIA", name: "Calais Campbell", position: "DT", depthOrder: 1, age: 40, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "Kader Kohou", position: "CB", depthOrder: 1, age: 25, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIA", name: "David Long Jr", position: "LB", depthOrder: 1, age: 27, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },

  // ========== MIN - Minnesota Vikings ==========
  { teamCode: "MIN", name: "JJ McCarthy", position: "QB", depthOrder: 1, age: 22, capHit: 6.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Aaron Jones", position: "RB", depthOrder: 1, age: 31, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Justin Jefferson", position: "WR", depthOrder: 1, age: 27, capHit: 35.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Jordan Addison", position: "WR", depthOrder: 2, age: 24, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Jalen Nailor", position: "WR", depthOrder: 3, age: 26, capHit: 1.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "TJ Hockenson", position: "TE", depthOrder: 1, age: 29, capHit: 14.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Christian Darrisaw", position: "OT", depthOrder: 1, age: 27, capHit: 7.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Brian O'Neill", position: "OT", depthOrder: 2, age: 30, capHit: 16.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Garrett Bradbury", position: "OL", depthOrder: 1, age: 30, capHit: 6.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Ed Ingram", position: "OL", depthOrder: 2, age: 26, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Jonathan Greenard", position: "EDGE", depthOrder: 1, age: 28, capHit: 18.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Andrew Van Ginkel", position: "EDGE", depthOrder: 2, age: 30, capHit: 6.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Harrison Phillips", position: "DT", depthOrder: 1, age: 29, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Byron Murphy Jr", position: "CB", depthOrder: 1, age: 28, capHit: 12.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Harrison Smith", position: "S", depthOrder: 1, age: 37, capHit: 10.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "MIN", name: "Ivan Pace Jr", position: "LB", depthOrder: 1, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },

  // ========== NE - New England Patriots ==========
  { teamCode: "NE", name: "Drake Maye", position: "QB", depthOrder: 1, age: 23, capHit: 7.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Jacoby Brissett", position: "QB", depthOrder: 2, age: 33, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Rhamondre Stevenson", position: "RB", depthOrder: 1, age: 27, capHit: 10.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Kendrick Bourne", position: "WR", depthOrder: 1, age: 30, capHit: 5.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "DeMario Douglas", position: "WR", depthOrder: 2, age: 24, capHit: 1.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Ja'Lynn Polk", position: "WR", depthOrder: 3, age: 23, capHit: 2.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Hunter Henry", position: "TE", depthOrder: 1, age: 31, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Caedan Wallace", position: "OT", depthOrder: 1, age: 25, capHit: 2.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Mike Onwenu", position: "OT", depthOrder: 2, age: 27, capHit: 14.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "David Andrews", position: "OL", depthOrder: 1, age: 33, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Cole Strange", position: "OL", depthOrder: 2, age: 27, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Harold Landry", position: "EDGE", depthOrder: 1, age: 29, capHit: 14.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Matthew Judon", position: "EDGE", depthOrder: 2, age: 33, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Keion White", position: "EDGE", depthOrder: 3, age: 25, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Davon Godchaux", position: "DT", depthOrder: 1, age: 30, capHit: 9.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Christian Gonzalez", position: "CB", depthOrder: 1, age: 23, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Carlton Davis", position: "CB", depthOrder: 2, age: 29, capHit: 20.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Kyle Dugger", position: "S", depthOrder: 1, age: 29, capHit: 12.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NE", name: "Ja'Whaun Bentley", position: "LB", depthOrder: 1, age: 28, capHit: 6.5, contractYears: 1, status: "active", sport: "NFL" },

  // ========== NO - New Orleans Saints ==========
  { teamCode: "NO", name: "Derek Carr", position: "QB", depthOrder: 1, age: 35, capHit: 40.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Jake Haener", position: "QB", depthOrder: 2, age: 26, capHit: 1.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Alvin Kamara", position: "RB", depthOrder: 1, age: 31, capHit: 15.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Chris Olave", position: "WR", depthOrder: 1, age: 25, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "AT Perry", position: "WR", depthOrder: 2, age: 24, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Juwan Johnson", position: "TE", depthOrder: 1, age: 28, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Ryan Ramczyk", position: "OT", depthOrder: 1, age: 31, capHit: 20.0, contractYears: 1, status: "injured", sport: "NFL" },
  { teamCode: "NO", name: "Trevor Penning", position: "OT", depthOrder: 2, age: 26, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Erik McCoy", position: "OL", depthOrder: 1, age: 28, capHit: 11.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Cesar Ruiz", position: "OL", depthOrder: 2, age: 27, capHit: 10.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Cameron Jordan", position: "EDGE", depthOrder: 1, age: 37, capHit: 15.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Chase Young", position: "EDGE", depthOrder: 2, age: 27, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Bryan Bresee", position: "DT", depthOrder: 1, age: 24, capHit: 5.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Demario Davis", position: "LB", depthOrder: 1, age: 36, capHit: 11.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Tyrann Mathieu", position: "S", depthOrder: 1, age: 34, capHit: 9.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NO", name: "Paulson Adebo", position: "CB", depthOrder: 1, age: 26, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },

  // ========== NYG - New York Giants ==========
  { teamCode: "NYG", name: "Russell Wilson", position: "QB", depthOrder: 1, age: 38, capHit: 10.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Tommy DeVito", position: "QB", depthOrder: 2, age: 27, capHit: 1.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Malik Nabers", position: "WR", depthOrder: 1, age: 22, capHit: 6.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Darius Slayton", position: "WR", depthOrder: 2, age: 28, capHit: 6.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Wan'Dale Robinson", position: "WR", depthOrder: 3, age: 24, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Darren Waller", position: "TE", depthOrder: 1, age: 33, capHit: 11.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Andrew Thomas", position: "OT", depthOrder: 1, age: 26, capHit: 18.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Evan Neal", position: "OT", depthOrder: 2, age: 25, capHit: 7.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "John Michael Schmitz", position: "OL", depthOrder: 1, age: 25, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Dexter Lawrence", position: "DT", depthOrder: 1, age: 27, capHit: 22.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Kayvon Thibodeaux", position: "EDGE", depthOrder: 1, age: 25, capHit: 6.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Brian Burns", position: "EDGE", depthOrder: 2, age: 27, capHit: 25.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Bobby Okereke", position: "LB", depthOrder: 1, age: 29, capHit: 10.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Deonte Banks", position: "CB", depthOrder: 1, age: 24, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYG", name: "Jevon Holland", position: "S", depthOrder: 1, age: 25, capHit: 12.0, contractYears: 3, status: "active", sport: "NFL" },

  // ========== NYJ - New York Jets ==========
  { teamCode: "NYJ", name: "Justin Fields", position: "QB", depthOrder: 1, age: 27, capHit: 20.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Breece Hall", position: "RB", depthOrder: 1, age: 24, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Garrett Wilson", position: "WR", depthOrder: 1, age: 25, capHit: 6.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Mike Williams", position: "WR", depthOrder: 2, age: 31, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Allen Lazard", position: "WR", depthOrder: 3, age: 30, capHit: 9.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Tyler Conklin", position: "TE", depthOrder: 1, age: 29, capHit: 7.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Tyron Smith", position: "OT", depthOrder: 1, age: 35, capHit: 11.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Morgan Moses", position: "OT", depthOrder: 2, age: 33, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Alijah Vera-Tucker", position: "OL", depthOrder: 1, age: 26, capHit: 5.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Joe Tippmann", position: "OL", depthOrder: 2, age: 25, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Mazi Smith", position: "DT", depthOrder: 1, age: 25, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Jermaine Johnson II", position: "EDGE", depthOrder: 1, age: 26, capHit: 4.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Will McDonald IV", position: "EDGE", depthOrder: 2, age: 25, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "CJ Mosley", position: "LB", depthOrder: 1, age: 33, capHit: 16.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Tony Adams", position: "S", depthOrder: 1, age: 26, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "NYJ", name: "Adonai Mitchell", position: "WR", depthOrder: 3, age: 23, capHit: 3.0, contractYears: 3, status: "active", sport: "NFL" },

  // ========== PHI - Philadelphia Eagles ==========
  { teamCode: "PHI", name: "Jalen Hurts", position: "QB", depthOrder: 1, age: 28, capHit: 51.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Kenny Pickett", position: "QB", depthOrder: 2, age: 27, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Saquon Barkley", position: "RB", depthOrder: 1, age: 29, capHit: 12.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "AJ Brown", position: "WR", depthOrder: 1, age: 28, capHit: 32.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "DeVonta Smith", position: "WR", depthOrder: 2, age: 27, capHit: 25.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Britain Covey", position: "WR", depthOrder: 3, age: 28, capHit: 1.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Dallas Goedert", position: "TE", depthOrder: 1, age: 30, capHit: 14.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Jordan Mailata", position: "OT", depthOrder: 1, age: 28, capHit: 18.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Lane Johnson", position: "OT", depthOrder: 2, age: 36, capHit: 18.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Landon Dickerson", position: "OL", depthOrder: 1, age: 27, capHit: 18.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Cam Jurgens", position: "OL", depthOrder: 2, age: 25, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Jaelan Phillips", position: "EDGE", depthOrder: 1, age: 26, capHit: 12.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Josh Sweat", position: "EDGE", depthOrder: 2, age: 28, capHit: 12.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Jalen Carter", position: "DT", depthOrder: 1, age: 24, capHit: 6.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Darius Slay", position: "CB", depthOrder: 1, age: 34, capHit: 17.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Jaire Alexander", position: "CB", depthOrder: 2, age: 28, capHit: 20.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Quinyon Mitchell", position: "CB", depthOrder: 3, age: 24, capHit: 3.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "CJ Gardner-Johnson", position: "S", depthOrder: 1, age: 28, capHit: 9.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PHI", name: "Nakobe Dean", position: "LB", depthOrder: 1, age: 24, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== PIT - Pittsburgh Steelers ==========
  { teamCode: "PIT", name: "Aaron Rodgers", position: "QB", depthOrder: 1, age: 42, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Najee Harris", position: "RB", depthOrder: 1, age: 28, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "DK Metcalf", position: "WR", depthOrder: 1, age: 28, capHit: 24.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "George Pickens", position: "WR", depthOrder: 2, age: 25, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Van Jefferson", position: "WR", depthOrder: 3, age: 29, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Calvin Austin III", position: "WR", depthOrder: 4, age: 26, capHit: 1.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Pat Freiermuth", position: "TE", depthOrder: 1, age: 27, capHit: 9.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Dan Moore Jr", position: "OT", depthOrder: 1, age: 27, capHit: 4.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Broderick Jones", position: "OT", depthOrder: 2, age: 24, capHit: 5.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Isaac Seumalo", position: "OL", depthOrder: 1, age: 31, capHit: 9.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Nate Herbig", position: "OL", depthOrder: 2, age: 27, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "TJ Watt", position: "EDGE", depthOrder: 1, age: 31, capHit: 28.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Alex Highsmith", position: "EDGE", depthOrder: 2, age: 28, capHit: 15.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Cameron Heyward", position: "DT", depthOrder: 1, age: 37, capHit: 16.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Elandon Roberts", position: "LB", depthOrder: 1, age: 30, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Minkah Fitzpatrick", position: "S", depthOrder: 1, age: 29, capHit: 18.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "PIT", name: "Joey Porter Jr", position: "CB", depthOrder: 1, age: 25, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== SEA - Seattle Seahawks ==========
  { teamCode: "SEA", name: "Sam Darnold", position: "QB", depthOrder: 1, age: 29, capHit: 33.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Kenneth Walker III", position: "RB", depthOrder: 1, age: 25, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Jaxon Smith-Njigba", position: "WR", depthOrder: 1, age: 23, capHit: 4.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Rashid Shaheed", position: "WR", depthOrder: 2, age: 26, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Tyler Lockett", position: "WR", depthOrder: 3, age: 33, capHit: 15.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Noah Fant", position: "TE", depthOrder: 1, age: 28, capHit: 8.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Charles Cross", position: "OT", depthOrder: 1, age: 24, capHit: 5.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Abraham Lucas", position: "OT", depthOrder: 2, age: 27, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Laken Tomlinson", position: "OL", depthOrder: 1, age: 33, capHit: 9.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Uchenna Nwosu", position: "EDGE", depthOrder: 1, age: 28, capHit: 11.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Boye Mafe", position: "EDGE", depthOrder: 2, age: 26, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Leonard Williams", position: "DT", depthOrder: 1, age: 31, capHit: 21.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Devon Witherspoon", position: "CB", depthOrder: 1, age: 24, capHit: 5.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Riq Woolen", position: "CB", depthOrder: 2, age: 26, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Julian Love", position: "S", depthOrder: 1, age: 27, capHit: 9.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SEA", name: "Tyrel Dodson", position: "LB", depthOrder: 1, age: 27, capHit: 5.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== SF - San Francisco 49ers ==========
  { teamCode: "SF", name: "Brock Purdy", position: "QB", depthOrder: 1, age: 26, capHit: 5.2, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Brandon Allen", position: "QB", depthOrder: 2, age: 32, capHit: 1.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Christian McCaffrey", position: "RB", depthOrder: 1, age: 30, capHit: 16.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Brandon Aiyuk", position: "WR", depthOrder: 1, age: 27, capHit: 28.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Jauan Jennings", position: "WR", depthOrder: 2, age: 28, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "George Kittle", position: "TE", depthOrder: 1, age: 32, capHit: 15.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Trent Williams", position: "OT", depthOrder: 1, age: 37, capHit: 24.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Colton McKivitz", position: "OT", depthOrder: 2, age: 28, capHit: 5.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Aaron Banks", position: "OL", depthOrder: 1, age: 27, capHit: 4.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Jake Brendel", position: "OL", depthOrder: 2, age: 32, capHit: 4.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Nick Bosa", position: "EDGE", depthOrder: 1, age: 28, capHit: 34.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Leonard Floyd", position: "EDGE", depthOrder: 2, age: 32, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Javon Hargrave", position: "DT", depthOrder: 1, age: 31, capHit: 17.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Fred Warner", position: "LB", depthOrder: 1, age: 29, capHit: 19.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Deommodore Lenoir", position: "CB", depthOrder: 1, age: 26, capHit: 2.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "SF", name: "Talanoa Hufanga", position: "S", depthOrder: 1, age: 25, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },

  // ========== TB - Tampa Bay Buccaneers ==========
  { teamCode: "TB", name: "Baker Mayfield", position: "QB", depthOrder: 1, age: 31, capHit: 30.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Kyle Trask", position: "QB", depthOrder: 2, age: 28, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Bucky Irving", position: "RB", depthOrder: 1, age: 23, capHit: 1.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Rachaad White", position: "RB", depthOrder: 2, age: 26, capHit: 2.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Mike Evans", position: "WR", depthOrder: 1, age: 33, capHit: 22.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Chris Godwin", position: "WR", depthOrder: 2, age: 29, capHit: 15.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Jalen McMillan", position: "WR", depthOrder: 3, age: 24, capHit: 2.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Cade Otton", position: "TE", depthOrder: 1, age: 26, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Tristan Wirfs", position: "OT", depthOrder: 1, age: 26, capHit: 22.0, contractYears: 4, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Luke Goedeke", position: "OT", depthOrder: 2, age: 27, capHit: 2.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Robert Hainsey", position: "OL", depthOrder: 1, age: 27, capHit: 3.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Vita Vea", position: "DT", depthOrder: 1, age: 30, capHit: 17.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Shaquil Barrett", position: "EDGE", depthOrder: 1, age: 33, capHit: 12.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Joe Tryon-Shoyinka", position: "EDGE", depthOrder: 2, age: 26, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Lavonte David", position: "LB", depthOrder: 1, age: 35, capHit: 10.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Devin White", position: "LB", depthOrder: 2, age: 27, capHit: 12.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Jamel Dean", position: "CB", depthOrder: 1, age: 29, capHit: 13.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TB", name: "Antoine Winfield Jr", position: "S", depthOrder: 1, age: 27, capHit: 21.0, contractYears: 3, status: "active", sport: "NFL" },

  // ========== TEN - Tennessee Titans ==========
  { teamCode: "TEN", name: "Will Levis", position: "QB", depthOrder: 1, age: 25, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Mason Rudolph", position: "QB", depthOrder: 2, age: 30, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Tony Pollard", position: "RB", depthOrder: 1, age: 28, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Calvin Ridley", position: "WR", depthOrder: 1, age: 31, capHit: 20.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Treylon Burks", position: "WR", depthOrder: 2, age: 25, capHit: 4.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Nick Westbrook-Ikhine", position: "WR", depthOrder: 3, age: 28, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Chigoziem Okonkwo", position: "TE", depthOrder: 1, age: 25, capHit: 1.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "JC Latham", position: "OT", depthOrder: 1, age: 22, capHit: 6.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Nicholas Petit-Frere", position: "OT", depthOrder: 2, age: 25, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Lloyd Cushenberry", position: "OL", depthOrder: 1, age: 27, capHit: 5.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Peter Skoronski", position: "OL", depthOrder: 2, age: 24, capHit: 5.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Arden Key", position: "EDGE", depthOrder: 1, age: 29, capHit: 6.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Jeffery Simmons", position: "DT", depthOrder: 1, age: 29, capHit: 23.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "L'Jarius Sneed", position: "CB", depthOrder: 1, age: 28, capHit: 14.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "TEN", name: "Amani Hooker", position: "S", depthOrder: 1, age: 27, capHit: 8.0, contractYears: 2, status: "active", sport: "NFL" },

  // ========== WAS - Washington Commanders ==========
  { teamCode: "WAS", name: "Jayden Daniels", position: "QB", depthOrder: 1, age: 24, capHit: 8.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Marcus Mariota", position: "QB", depthOrder: 2, age: 33, capHit: 3.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Brian Robinson Jr", position: "RB", depthOrder: 1, age: 26, capHit: 2.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Terry McLaurin", position: "WR", depthOrder: 1, age: 30, capHit: 23.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Deebo Samuel", position: "WR", depthOrder: 2, age: 29, capHit: 5.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Jahan Dotson", position: "WR", depthOrder: 3, age: 25, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Luke McCaffrey", position: "WR", depthOrder: 4, age: 24, capHit: 1.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Zach Ertz", position: "TE", depthOrder: 1, age: 36, capHit: 7.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Brandon Coleman", position: "OT", depthOrder: 1, age: 23, capHit: 3.5, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Andrew Wylie", position: "OT", depthOrder: 2, age: 30, capHit: 6.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Nick Allegretti", position: "OL", depthOrder: 1, age: 29, capHit: 7.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Sam Cosmi", position: "OL", depthOrder: 2, age: 27, capHit: 3.5, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Jonathan Allen", position: "DT", depthOrder: 1, age: 31, capHit: 22.0, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Daron Payne", position: "DT", depthOrder: 2, age: 28, capHit: 19.0, contractYears: 3, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Bobby Wagner", position: "LB", depthOrder: 1, age: 36, capHit: 11.0, contractYears: 1, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Emmanuel Forbes", position: "CB", depthOrder: 1, age: 24, capHit: 3.5, contractYears: 2, status: "active", sport: "NFL" },
  { teamCode: "WAS", name: "Kamren Curl", position: "S", depthOrder: 1, age: 26, capHit: 6.0, contractYears: 2, status: "active", sport: "NFL" },
];
